"""Inicjalizacja bazy danych

Revision ID: ee72becf7211
Revises: 
Create Date: 2025-02-07 00:04:13.321233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee72becf7211'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kandydaci',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imie', sa.String(length=100), nullable=False),
    sa.Column('nazwisko', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('telefon', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('data_kontaktu', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('ogłoszenie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tytul', sa.String(length=120), nullable=False),
    sa.Column('opis', sa.Text(), nullable=False),
    sa.Column('platforma', sa.String(length=100), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=False),
    sa.Column('data_publikacji', sa.Date(), nullable=False),
    sa.Column('data_wygasniecia', sa.Date(), nullable=False),
    sa.Column('data_utworzenia', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('szkolenie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temat', sa.String(length=120), nullable=False),
    sa.Column('opis', sa.Text(), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kandydat_id', sa.Integer(), nullable=False),
    sa.Column('data_zatrudnienia', sa.Date(), nullable=False),
    sa.Column('stanowisko', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['kandydat_id'], ['kandydaci.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spotkanie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kandydat_id', sa.Integer(), nullable=False),
    sa.Column('telefon', sa.String(length=20), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('opis', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['kandydat_id'], ['kandydaci.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spotkanie')
    op.drop_table('historia')
    op.drop_table('szkolenie')
    op.drop_table('ogłoszenie')
    op.drop_table('kandydaci')
    # ### end Alembic commands ###
